name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Debug & Bench
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt-get update -y
            sudo apt-get install g++-13
            echo "CXX=$(which g++-13)" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install llvm
            echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
          fi

      - name: Setup environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: echo "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build
        run: make debug CXX=${{ env.CXX }}

      - name: Run Bench (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: ./baryonyx bench

      - name: Run Bench (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: .\baryonyx.exe bench

      - name: Clean
        run: make clean