name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Debug
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Linux environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install g++-13
          echo "CXX=$(which g++-13)" >> $GITHUB_ENV

      - name: Setup Windows environment
        if: matrix.os == 'windows-latest'
        run: |
          echo "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup macOS environment
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm
          echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV

      - name: Build
        run: make debug CXX=${{ env.CXX }}

      - name: Clean
        run: make clean