name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build Release & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Linux environment
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install g++-13 cmake -y
          echo "CXX=$(which g++-13)" >> $GITHUB_ENV

      - name: Build Tests
        run: |
          mkdir build
          cd build
          cmake ../tests -DCMAKE_BUILD_TYPE=Release
          make

      - name: Run Tests
        run: ./build/BaryonyxTests

      - name: Clean
        run: make clean