name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build Release & Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest GCC
        run: |
          sudo add-apt-repository universe -y
          sudo apt-get update -y
          sudo apt-get install g++-14 gcc-14 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14
          sudo apt-get install gcc-14-multilib g++-14-multilib -y

      - name: Install cmake
        run: |
          sudo apt update -y
          sudo apt install cmake

      - name: Set environment variables
        run: |
          echo "CC=$(which gcc-14)" >> $GITHUB_ENV
          echo "CXX=$(which g++-14)" >> $GITHUB_ENV

      - name: Build Tests
        run: |
          mkdir build
          cd build
          cmake ../tests -DCMAKE_BUILD_TYPE=Release
          make

      - name: Run Tests
        run: ./build/NibbleTests

      - name: Clean
        run: make clean